openapi: 3.0.0
info:
  title: Hall-E API
  version: 1.0.0
  description: API de l'application Hall-E
  contact:
    name: hall-esport38@gmail.com
servers:
  - url: http://localhost:5000

paths:
  /api/v1/user/sign-in:
    post:
      summary: Inscription d'un utilisateur
      tags: [Users]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              oneOf:
                - $ref: '#/components/schemas/Consumer'
                - $ref: '#/components/schemas/Bar'
            examples: 
              consumer:
                summary: An example of a consumer
                value:
                  firstName: John
                  lastName: Doe
                  password: 
                  email: johndoe@example.com
                  role: consumer
              bar: 
                summary: An example of a bar
                value:
                  firstName: John
                  lastName: Doe
                  password: 
                  email: johndoe@example.com
                  role: bar
      responses:
        200:
          description: The user was successfully created
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: success 

  /api/v1/user/connexion:
    post:
      summary: Connexion d'un Utilisateur
      tags: [Users]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Connexion'      
      responses:
        200:
          description: The consumer/bar was successfully connexion
          content:
            application/json:
              schema:
                type: object
              examples:
                consumer:
                  summary: An example of a consumer
                  value:
                    id: 1
                    firstName: John
                    lastName: Doe
                    isAuthenticated: true 
                    email: johndoe@example.com
                    role: consumer
                bar: 
                  summary: An example of a bar
                  value:
                    id: 1
                    firstName: John
                    lastName: Doe
                    isAuthenticated: true 
                    email: johndoe@example.com
                    role: bar
        401:
          description: Inforamtions is missing
          content:
            text/paint:
              schema:
                type: string
              examples: 
                
  /api/v1/user/:
      delete:
        summary: Supprésion d'un Utilisateur
        tags: [Users]
        requestBody:
          required: true
          content:
            application/json:
              schema:
                schema:
                $ref: '#/components/schemas/Delete'
              examples:
                consumer:
                  summary: An example of a consumer
                  value:
                    id: 1
                    role: consumer
                bar: 
                  summary: An example of a bar
                  value:
                    id: 1
                    role: bar
        responses:
          200:
            description: The consumer/bar was successfully delete compte
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    message: 
                      type: string
                      description: "message success"
                    isDelete: 
                      type: bool
                      description: boolean de retour
                example:
                  message: "User delete with success"
                  isDelete: true
          500:
            description: Erreur server
            content:
              text/paint:
                schema:
                  type: string
                  example: Erreur server


components:
  schemas:
    Consumer:
      type: object
      properties:
        firstName:
          type: string
          description: Prénom de l'utilisateur
        lastName:
          type: string
          description: Nom de l'utilisateur
        password:
          type: string
          description: Token d'authentification
        email:
          type: string
          description: The email of the user
        role: 
          type: string
          enum: [consumer]
          description: Role of user 
      required:
        - firstName
        - lastName
        - email
        - password
        - role
    
    Delete:
      type: object
      properties:
        id:
          type: string
          description: user id
        role: 
          type: string
          description: Role of user  
      required:
        - id
        - role

    Connexion:
      type: object
      properties:
        password:
          type: string
          description: Token d'authentification
        email:
          type: string
          description: The email of the user

      required:
        - email
        - password
      example:
        password: 
        email: johndoe@example.com


    Bar:
      type: object
      required:
        - email
        - role
      properties:
        role:
          type: string
          enum: [bar]
          description: Role de l'utilisateur
        email:
          type: string
          description: Email de l'utilisateur
      example:
        email: johndoe@example.com
        role: bar 
        
        


